### ISSUE TITLE
[Bug] Duplicate identifier 'LuaIterable'

### ISSUE THREAD

**Issue by Toliak** [TypeScriptToLua/lua-types#20]
**Description**

When I use `lua-types@2.8.0` and `typescript-to-lua@0.39.0` and execute `tstl` command the error appears:
```
node_modules/lua-types/core/global.d.ts:10:6 - error TS2300: Duplicate identifier 'LuaIterable'.

10 type LuaIterable<T> = Iterable<T> & { readonly __internal__: unique symbol };
        ~~~~~~~~~~~

  node_modules/typescript-to-lua/language-extensions/index.d.ts:73:14
    73 declare type LuaIterable<TValue, TState = undefined> = Iterable<TValue> &
                    ~~~~~~~~~~~
    'LuaIterable' was also declared here.

node_modules/typescript-to-lua/language-extensions/index.d.ts:73:14 - error TS2300: Duplicate identifier 'LuaIterable'.

73 declare type LuaIterable<TValue, TState = undefined> = Iterable<TValue> &
                ~~~~~~~~~~~

  node_modules/lua-types/core/global.d.ts:10:6
    10 type LuaIterable<T> = Iterable<T> & { readonly __internal__: unique symbol };
            ~~~~~~~~~~~
    'LuaIterable' was also declared here.
```

**Environment**
My package.json:
[Link](https://github.com/mtasa-typescript/resource-boilerplate/blob/41306d18dd174c3d17dba866c283bebddca703bb/package.json)

My tsconfig.json:
[Link](https://github.com/mtasa-typescript/resource-boilerplate/blob/41306d18dd174c3d17dba866c283bebddca703bb/tsconfig.json)

**How to reproduce**

```
git clone https://github.com/mtasa-typescript/resource-boilerplate types-issue-20
cd types-issue-20
git checkout 6fd89f

npm install

npm run build
```

The first block initializes configs
The second block installs all dependencies
And the last block triggers `tstl` command

**Additional information**
The same issue with `/// <reference types="lua-types/5.1" />`

**Comment by RobinCodeX** [comment]
This error requires you to remove `"typescript-to-lua/language-extensions"` in `tsconfig.json`.

Reference: https://github.com/TypeScriptToLua/TypeScriptToLua/blob/759090a3aabc744f81883bb0d39929ecc740258c/language-extensions/index.d.ts#L73-L75
