### ISSUE TITLE
Indicate that pairs and ipairs give non-nullable values

### ISSUE THREAD

**Issue by GlassBricks** [TypeScriptToLua/lua-types#29]
`pairs` and `ipairs` never return `nil` values (`undefined/null` in typescript).
It would be useful if this was reflected in the signature of pairs/ipairs (using `NonNullable<>`), for lua-iterating types like `Partial<...>` or types with optional properties.

**Comment by Perryvw** [comment]
Sounds good to me, PRs welcome

**Comment by Zamiell** [comment]
close this now?
