### ISSUE TITLE
Should not contain child node_modules

### ISSUE THREAD

**Issue by RobinCodeX** [TypeScriptToLua/lua-types#43]
Directoy of lua-types v2.10.1
![image](https://user-images.githubusercontent.com/8408783/132810366-910c9fde-bdbd-4563-a51e-e3c6ec19844b.png)
This will cause conflicts with the @moddota/dota-lua-types

**Comment by GlassBricks** [comment]
When I download v2.10.1, it doesn't contain any folders besides `core` and `special`, no node_modules.

have you tried force-reinstalling, or do you still have a npm link or yarn link up?

**Comment by RobinCodeX** [comment]
@GlassBricks I've been using `yarn install`, just now I deleted the `node_modules` directory and reinstalled using `npm install` and got the same result, which seems to be submodules automatically installed by yarn and npm.

I think it maybe a version problem. I use typescript-to-lua v1.0.1, but lua-types still dependent on `"typescript-to-lua": "^0.39.0"`.

**Comment by Perryvw** [comment]
@RobinCodeX I was testing some stuff and updated the version myself like you noticed. I have just release a new version, please give it a try and test if this works.

**Comment by RobinCodeX** [comment]
@Perryvw I tested it and it's fine
